### PR TITLE
Fixed doxygen index page

### PR DESCRIPTION
**Pull request by evaherrada**

### CODE REVIEW

**Comment by ladyada** [comment]
hi what are you fixing here, the ```* @file     Adafruit_EEPROM_I2C.cpp```??

**Comment by evaherrada** [comment]
@ladyada not really. Some of the `#if`s used to detect the platform the code is running on are causing Doxygen to ignore large portions of the file, in some cases causing the index.html to not have any text. 
So I'm having doxygen ignore them, and in the process also trying to fix other stuff that's making it not render correctly, such as a missing `@mainpage`, and I'm trying to make some of the formatting slightly more consistent with what the Adafruit docs on this stuff calls for. 
Bryan did also ask me to also make doxygen fully pass by documenting everything that isn't documented already, however, there were many things that I didn't really know what they were, so my plan was to just get index.html to have the right text, and then revisit fully documenting everything when Bryan was back online.

**Comment by ladyada** [comment]
hmm what section of index.html is missing that is #if related? it looks ok to me

**Comment by evaherrada** [comment]
@ladyada Actually, yeah, I think you're right about it not being #if related. This library was only missing an `@mainpage` to get index.html to render correctly. Here's what it currently looks like:
Screenshot from 2020-05-20 18-29-28
And here's what it looks like after I added `@mainpage`
Screenshot from 2020-05-20 18-30-28
I guess I should probably go back and check what happens if I remove the `@cond`s but keep the other changes.

**Comment by ladyada** [comment]
ok yah if you dont mind, remove the cond's cause yu dont need em and i think they could cause confusion :/

**Comment by evaherrada** [comment]
@ladyada Ok. Will do.

**Pull request merged**
